project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  render:
    - '*.qmd' # Render all .qmd files in the root directory
    - '!exams/' # Ignore the entire exams folder
    - '!quizzes/' # Ignore the entire quizzes folder
    - '!book/' # Ignore the entire quizzes folder
    - '!rc01_writeup/'

website:
  title: 'MATH411'
  navbar:
    tools:
      - icon: github
        href: https://github.com/nlunce/math411
    left:
      - href: ./homework/index.html
        text: HOMEWORK
      - href: ./reality-checks/index.html
        text: REALITY CHECKS
      - href: ./notes/index.html
        text: NOTES
      - href: ./index.html
        text: SCHEDULE

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
