project:
  type: website
  preview:
    port: 3000
    browser: true
    watch-inputs: true
    navigate: true
  output-dir: docs
  render:
    - '*.qmd'
    - '!exams/'
    - '!quizzes/'
    - '!book/'
    - '!rc01_writeup/'

website:
  title: 'MATH411'
  navbar:
    tools:
      - icon: github
        href: https://github.com/nlunce/math411
    left:
      - href: ./homework/index.html
        text: HOMEWORK
      - href: ./reality-checks/index.html
        text: REALITY CHECKS
      - href: ./notes/index.html
        text: NOTES
      - href: ./index.html
        text: SCHEDULE

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

execute:
  warning: false
  message: false

jupyter: python3
