---
title: 'FALL 2024 - SCHEDULE'
---

<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }
    th, td {
        border: 1px solid #ddd;
        text-align: center;
        vertical-align: top;
        font-family: Arial, sans-serif;
        position: relative;
    }
    th {
        background-color: #f2f2f2;
        padding: 5px;
    }
    td {
        height: 100px;
    }
    .week-col {
        width: 10%; /* Fixed width for the "Week" column */
    }
    .content-cell {
        width: 18%; /* Adjusted width for other columns to evenly fill the rest of the table */
    }
    .date {
        position: absolute;
        top: 5px;
        left: 5px;
        font-size: 0.8em;
        color: #666;
    }
</style>

<table>
    <tr>
        <th class="week-col">Week</th>
        <th class="content-cell">Monday</th>
        <th class="content-cell">Tuesday</th>
        <th class="content-cell">Wednesday</th>
        <th class="content-cell">Thursday</th>
        <th class="content-cell">Friday</th>
    </tr>
    <tr>
        <td class="week-col">1</td>
        <td><span class="date">16</span><br>Chapter 1</td>
        <td><span class="date">17</span></td>
        <td><span class="date">18</span><br>Chapter 1</td>
        <td><span class="date">19</span></td>
        <td><span class="date">20</span><br>Chapter 1</td>
    </tr>
    <tr>
        <td class="week-col">2</td>
        <td><span class="date">23</span><br>Add/Drop<br>Chapter 1</td>
        <td><span class="date">24</span></td>
        <td><span class="date">25</span><br>Chapter 1<br><strong>Quiz 1</strong></td>
        <td><span class="date">26</span></td>
        <td><span class="date">27</span><br>Chapter 3</td>
    </tr>
    <tr>
        <td class="week-col">3</td>
        <td><span class="date">30</span><br>Chapter 3</td>
        <td><span class="date">1</span></td>
        <td><span class="date">2</span><br>Chapter 3<br><strong>Quiz 2</strong></td>
        <td><span class="date">3</span></td>
        <td><span class="date">4</span><br>Chapter 3</td>
    </tr>
    <tr>
        <td class="week-col">4</td>
        <td><span class="date">7</span><br>Chapter 3<br><strong>Reality Check 1</strong></td>
        <td><span class="date">8</span><br>No W drop date</td>
        <td><span class="date">9</span><br>Chapter 5<br><strong>Quiz 3</strong></td>
        <td><span class="date">10</span></td>
        <td><span class="date">11</span><br>Chapter 5</td>
    </tr>
    <tr>
        <td class="week-col">5</td>
        <td><span class="date">14</span><br>Chapter 5</td>
        <td><span class="date">15</span></td>
        <td><span class="date">16</span><br>Chapter 5<br><strong>Quiz 4</strong></td>
        <td><span class="date">17</span></td>
        <td><span class="date">18</span><br>Chapter 5</td>
    </tr>
    <tr>
        <td class="week-col">6</td>
        <td><span class="date">21</span><br>Exam 1 Review<br><strong>Exam 1-2 Opens</strong></td>
        <td><span class="date">22</span></td>
        <td><span class="date">23</span><br><strong>Exam 1-1</strong><br><strong>In Class</strong></td>
        <td><span class="date">24</span><br><strong>Exam 1-2 Closes</strong></td>
        <td><span class="date">25</span><br>Chapter 2</td>
    </tr>
    <tr>
        <td class="week-col">7</td>
        <td><span class="date">28</span><br>Chapter 2</td>
        <td><span class="date">29</span></td>
        <td><span class="date">30</span><br>Chapter 2</td>
        <td><span class="date">31</span></td>
        <td><span class="date">1</span><br>Chapter 2</td>
    </tr>
    <tr>
        <td class="week-col">8</td>
        <td><span class="date">4</span><br>Chapter 2</td>
        <td><span class="date">5</span></td>
        <td><span class="date">6</span><br>Chapter 4<br><strong>Quiz 5</strong></td>
        <td><span class="date">7</span></td>
        <td><span class="date">8</span><br>Chapter 4</td>
    </tr>
    <tr>
        <td class="week-col">9</td>
        <td><span class="date">11</span><br>Drop w/W date<br>Chapter 4<br><strong>2nd Reality Check</strong></td>
        <td><span class="date">12</span></td>
        <td><span class="date">13</span><br>Chapter 4<br><strong>Quiz 6</strong></td>
        <td><span class="date">14</span></td>
        <td><span class="date">15</span><br>Chapter 4</td>
    </tr>
    <tr>
        <td class="week-col">10</td>
        <td><span class="date">18</span><br>Chapter 4</td>
        <td><span class="date">19</span></td>
        <td><span class="date">20</span><br>Chapter 4</td>
        <td><span class="date">21</span></td>
        <td><span class="date">22</span><br>Exam 2 Review<br><strong>Exam 2-2 Opens</strong></td>
    </tr>
    <tr>
        <td class="week-col">11</td>
        <td><span class="date">25</span><br>Exam 2-1<br>In Class</td>
        <td><span class="date">26</span><br><strong>Exam 2-2 Closes</strong></td>
        <td><span class="date">27</span><br>No Classes</td>
        <td><span class="date">28</span><br>Holiday</td>
        <td><span class="date">29</span><br>Holiday</td>
    </tr>
    <tr>
        <td class="week-col">12</td>
        <td><span class="date">2</span><br>Chapter 10</td>
        <td><span class="date">3</span><br>Discontinuance</td>
        <td><span class="date">4</span><br>Chapter 10</td>
        <td><span class="date">5</span></td>
        <td><span class="date">6</span><br>Chapter 10<br>Quiz 7 (?)</td>
    </tr>
    <tr>
        <td class="week-col">13</td>
        <td><span class="date">9</span><br>Chapter 10</td>
        <td><span class="date">10</span></td>
        <td><span class="date">11</span><br>Chapter 10</td>
        <td><span class="date">12</span></td>
        <td><span class="date">13</span><br>Chapter 10<br><strong>Exam 3-2 Opens</strong></td>
    </tr>
    <tr>
        <td class="week-col">14</td>
        <td><span class="date">16</span><br>Last Day of Class</td>
        <td><span class="date">17</span><br><strong>10:30 Exam 3-1</strong><br><strong>Exam 3-2 Closes</strong><br><strong>3rd Reality Check</strong></td>
        <td><span class="date">18</span></td>
        <td><span class="date">19</span><br>Commencement</td>
        <td><span class="date">20</span></td>
    </tr>
</table>
